//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.App.DataAccessLayer.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuPrivilege
    {
        public int PrivilegeID { get; set; }
        public int MenuID { get; set; }
        public int RoleID { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanCreate { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual MenuMaster MenuMaster { get; set; }
    }
}
